# Generated by Django 4.2.7 on 2024-02-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='sequence_number',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
